-- User roles
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE public.user_role AS ENUM ('superadmin','admin','manager','waiter','kitchen');
  END IF;
END$$;

-- Hotel status
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'hotel_status') THEN
    CREATE TYPE public.hotel_status AS ENUM ('active','expired','disabled');
  END IF;
END$$;

-- Table status
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'table_status') THEN
    CREATE TYPE public.table_status AS ENUM ('available','occupied','reserved');
  END IF;
END$$;

-- Order status
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
    CREATE TYPE public.order_status AS ENUM ('pending','preparing','ready','completed','cancelled');
  END IF;
END$$;

-- Bill order type
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bill_order_type') THEN
    CREATE TYPE public.bill_order_type AS ENUM ('TABLE','ROOM','TAKEAWAY');
  END IF;
END$$;



CREATE TABLE IF NOT EXISTS public.hotels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  owner_name TEXT,
  owner_phone TEXT,
  owner_email TEXT,
  currency TEXT DEFAULT 'INR',
  timezone TEXT DEFAULT 'Asia/Kolkata',
  logo_url TEXT,
  phone TEXT,
  email TEXT,
  subscription_start TIMESTAMPTZ,
  subscription_end TIMESTAMPTZ,
  status public.hotel_status DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);



CREATE TABLE IF NOT EXISTS public.superadmins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  hashed_password TEXT NOT NULL,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);



BEGIN;

CREATE TABLE IF NOT EXISTS public.app_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  role public.user_role NOT NULL,
  email TEXT NOT NULL,
  name TEXT,
  phone TEXT,
  hashed_password TEXT NOT NULL,
  created_by BIGINT,
  enabled BOOLEAN DEFAULT true,
  auth_uid UUID,
  staff_code TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (email, hotel_id)
);

-- ✅ Safe UUID update by matching email
UPDATE public.app_users au
SET auth_uid = u.id
FROM auth.users u
WHERE au.email = u.email
  AND au.auth_uid IS NULL;  -- ✅ removed invalid empty string check

COMMIT;



BEGIN;

CREATE TABLE IF NOT EXISTS public.app_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  role public.user_role NOT NULL,
  email TEXT NOT NULL,
  name TEXT,
  phone TEXT,
  hashed_password TEXT NOT NULL,
  created_by BIGINT,
  enabled BOOLEAN DEFAULT true,
  auth_uid UUID,
  staff_code TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (email, hotel_id)
);

-- ✅ Safe UUID update by matching email
UPDATE public.app_users au
SET auth_uid = u.id
FROM auth.users u
WHERE au.email = u.email
  AND au.auth_uid IS NULL;  -- ✅ removed invalid empty string check

COMMIT;





CREATE TABLE IF NOT EXISTS public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (hotel_id, name)
);

CREATE TABLE IF NOT EXISTS public.menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.menu_categories(id),
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  description TEXT,
  veg BOOLEAN DEFAULT false,
  available BOOLEAN DEFAULT true,
  prep_time INT DEFAULT 0,
  tags TEXT[],
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);



CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  table_number INT NOT NULL,
  seats INT DEFAULT 4,
  status public.table_status DEFAULT 'available',
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (hotel_id, table_number)
);



CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  table_id BIGINT REFERENCES public.tables(id),
  waiter_id BIGINT REFERENCES public.app_users(id),
  kot_number TEXT,
  order_type public.bill_order_type DEFAULT 'TABLE',
  status public.order_status DEFAULT 'pending',
  subtotal NUMERIC,
  gst NUMERIC,
  discount NUMERIC,
  service_charge NUMERIC,
  total NUMERIC,
  billed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  menu_id BIGINT REFERENCES public.menus(id),
  qty INT DEFAULT 1,
  price NUMERIC,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES public.orders(id),
  amount NUMERIC,
  payment_method VARCHAR(20)
      DEFAULT 'CASH' CHECK (payment_method IN ('CASH','CARD','UPI')),
  created_at TIMESTAMPTZ DEFAULT now()
);



CREATE TABLE IF NOT EXISTS public.hotel_tax_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT UNIQUE REFERENCES public.hotels(id) ON DELETE CASCADE,
  gst_rate NUMERIC DEFAULT 18,
  service_charge NUMERIC DEFAULT 0,
  service_charge_enabled BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.kitchen_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  station_type TEXT,
  printer_id TEXT,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (hotel_id, name)
);





CREATE TABLE IF NOT EXISTS public.bills (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hotel_id BIGINT NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  bill_number VARCHAR(100) UNIQUE NOT NULL,

  item_discounts JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_discount NUMERIC(10,2) NOT NULL DEFAULT 0,
  discount_mode VARCHAR(10) NOT NULL DEFAULT 'FLAT'
      CHECK (discount_mode IN ('PERCENT','FLAT')),

  subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
  gst NUMERIC(10,2) NOT NULL DEFAULT 0,
  service_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(10,2) NOT NULL,

  payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH'
      CHECK (payment_method IN ('CASH','CARD','UPI')),
  status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
      CHECK (status IN ('DRAFT','PAID','CANCELLED')),

  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS bills_hotel_bill_number_idx
  ON public.bills (hotel_id, bill_number);

CREATE INDEX IF NOT EXISTS bills_hotel_idx ON public.bills (hotel_id);
CREATE INDEX IF NOT EXISTS bills_order_idx ON public.bills (order_id);

-- Enable RLS
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "rls_view_bills" ON public.bills;
CREATE POLICY "rls_view_bills" ON public.bills
FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.app_users au
    WHERE au.hotel_id = public.bills.hotel_id
      AND au.auth_uid = auth.uid()
  )
);

DROP POLICY IF EXISTS "rls_insert_bills" ON public.bills;
CREATE POLICY "rls_insert_bills" ON public.bills
FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.app_users au
    WHERE au.hotel_id = public.bills.hotel_id
      AND au.auth_uid = auth.uid()
  )
);

DROP POLICY IF EXISTS "rls_update_bills" ON public.bills;
CREATE POLICY "rls_update_bills" ON public.bills
FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.app_users au
    WHERE au.hotel_id = public.bills.hotel_id
      AND au.auth_uid = auth.uid()
  )
);

-- Triggers

-- Bill insert → update order
CREATE OR REPLACE FUNCTION public.trigger_update_order_on_bill()
RETURNS trigger AS $$
BEGIN
  UPDATE public.orders
  SET status = 'completed', billed_at = now()
  WHERE id = NEW.order_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS bill_created_trigger ON public.bills;
CREATE TRIGGER bill_created_trigger
AFTER INSERT ON public.bills
FOR EACH ROW EXECUTE FUNCTION public.trigger_update_order_on_bill();

-- Auto update bills.updated_at
CREATE OR REPLACE FUNCTION public.trigger_refresh_bills_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS bills_updated_at_trigger ON public.bills;
CREATE TRIGGER bills_updated_at_trigger
BEFORE UPDATE ON public.bills
FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_bills_updated_at();





BEGIN;

-- 01 ENUMS
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='user_role') THEN
  CREATE TYPE public.user_role AS ENUM ('superadmin','admin','manager','waiter','kitchen');
END IF; END$$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='hotel_status') THEN
  CREATE TYPE public.hotel_status AS ENUM ('active','expired','disabled');
END IF; END$$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='table_status') THEN
  CREATE TYPE public.table_status AS ENUM ('available','occupied','reserved');
END IF; END$$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='order_status') THEN
  CREATE TYPE public.order_status AS ENUM ('pending','preparing','ready','completed','cancelled');
END IF; END$$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='bill_order_type') THEN
  CREATE TYPE public.bill_order_type AS ENUM ('TABLE','ROOM','TAKEAWAY');
END IF; END$$;

-- 02 HOTELS
CREATE TABLE IF NOT EXISTS public.hotels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, address TEXT, city TEXT, state TEXT, pincode TEXT,
  owner_name TEXT, owner_phone TEXT, owner_email TEXT,
  currency TEXT DEFAULT 'INR', timezone TEXT DEFAULT 'Asia/Kolkata',
  logo_url TEXT, phone TEXT, email TEXT,
  subscription_start TIMESTAMPTZ, subscription_end TIMESTAMPTZ,
  status public.hotel_status DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now()
);

-- 03 SUPER ADMINS
CREATE TABLE IF NOT EXISTS public.superadmins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL, hashed_password TEXT NOT NULL,
  name TEXT, created_at TIMESTAMPTZ DEFAULT now()
);

-- 04 APP USERS
CREATE TABLE IF NOT EXISTS public.app_users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  role public.user_role NOT NULL, email TEXT NOT NULL,
  name TEXT, phone TEXT, hashed_password TEXT NOT NULL,
  created_by BIGINT, enabled BOOLEAN DEFAULT true,
  auth_uid UUID, staff_code TEXT UNIQUE, created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (email, hotel_id)
);

-- ✅ FIXED: removed invalid uuid comparison with ''
UPDATE public.app_users au
SET auth_uid = u.id
FROM auth.users u
WHERE au.email = u.email
  AND au.auth_uid IS NULL;

-- 05 MENU SYSTEM
CREATE TABLE IF NOT EXISTS public.menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  name TEXT, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE (hotel_id,name)
);

CREATE TABLE IF NOT EXISTS public.menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.menu_categories(id),
  name TEXT NOT NULL, price NUMERIC NOT NULL, description TEXT,
  veg BOOLEAN DEFAULT false, available BOOLEAN DEFAULT true,
  prep_time INT DEFAULT 0, tags TEXT[], image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 06 TABLES
CREATE TABLE IF NOT EXISTS public.tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  table_number INT NOT NULL, seats INT DEFAULT 4,
  status public.table_status DEFAULT 'available',
  created_at TIMESTAMPTZ DEFAULT now(), UNIQUE (hotel_id,table_number)
);

-- 07 ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  table_id BIGINT REFERENCES public.tables(id),
  waiter_id BIGINT REFERENCES public.app_users(id),
  kot_number TEXT, order_type public.bill_order_type DEFAULT 'TABLE',
  status public.order_status DEFAULT 'pending',
  subtotal NUMERIC, gst NUMERIC, discount NUMERIC, service_charge NUMERIC,
  total NUMERIC, billed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  menu_id BIGINT REFERENCES public.menus(id), qty INT DEFAULT 1, price NUMERIC,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS public.invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES public.orders(id),
  amount NUMERIC, payment_method VARCHAR(20) DEFAULT 'CASH'
    CHECK (payment_method IN ('CASH','CARD','UPI')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 08 TAX & KITCHEN
CREATE TABLE IF NOT EXISTS public.hotel_tax_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT UNIQUE REFERENCES public.hotels(id) ON DELETE CASCADE,
  gst_rate NUMERIC DEFAULT 18, service_charge NUMERIC DEFAULT 0,
  service_charge_enabled BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.kitchen_stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  name TEXT NOT NULL, station_type TEXT, printer_id TEXT,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (hotel_id,name)
);

-- 09 NOTIFICATIONS
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT REFERENCES public.hotels(id) ON DELETE CASCADE,
  role_target public.user_role, target_user_id BIGINT REFERENCES public.app_users(id)
    ON DELETE SET NULL,
  message TEXT, order_id BIGINT,
  is_read BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now()
);

-- 10 BILLS
CREATE TABLE IF NOT EXISTS public.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hotel_id BIGINT NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  bill_number VARCHAR(100) UNIQUE NOT NULL,
  item_discounts JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_discount NUMERIC(10,2) NOT NULL DEFAULT 0,
  discount_mode VARCHAR(10) NOT NULL DEFAULT 'FLAT'
    CHECK (discount_mode IN ('PERCENT','FLAT')),
  subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
  gst NUMERIC(10,2) NOT NULL DEFAULT 0,
  service_charge NUMERIC(10,2) NOT NULL DEFAULT 0,
  grand_total NUMERIC(10,2) NOT NULL,
  payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH'
    CHECK (payment_method IN ('CASH','CARD','UPI')),
  status VARCHAR(10) NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT','PAID','CANCELLED')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS bills_hotel_bill_number_idx ON public.bills(hotel_id,bill_number);
CREATE INDEX IF NOT EXISTS bills_hotel_idx ON public.bills(hotel_id);
CREATE INDEX IF NOT EXISTS bills_order_idx ON public.bills(order_id);

ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- Bill trigger order update
CREATE OR REPLACE FUNCTION public.trigger_update_order_on_bill()
RETURNS trigger AS $$
BEGIN
  UPDATE public.orders
  SET status = 'completed', billed_at = now()
  WHERE id = NEW.order_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS bill_created_trigger ON public.bills;
CREATE TRIGGER bill_created_trigger
AFTER INSERT ON public.bills
FOR EACH ROW EXECUTE FUNCTION public.trigger_update_order_on_bill();

-- Auto updated_at
CREATE OR REPLACE FUNCTION public.trigger_refresh_bills_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS bills_updated_at_trigger ON public.bills;
CREATE TRIGGER bills_updated_at_trigger
BEFORE UPDATE ON public.bills
FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_bills_updated_at();

COMMIT;
