const express = require('express');
const router = express.Router();
const auth = require('./auth');
const bootstrap = require('./bootstrap');
const superadmin = require('./superadmin');
const users = require('./users');
const hotels = require('./hotels');
const menu = require('./menu');
const categories = require('./categories');
const tables = require('./tables');
const stations = require('./stations');
const taxes = require('./taxes');
const general = require('./general');
const orders = require('./orders');
const invoices = require('./invoices');
const notifications = require('./notifications');
const bills = require('./bills');
const reports = require('./reports');
const debug = require('./debug');
const dashboard = require('./dashboard');

router.use('/auth', auth);
router.use('/bootstrap', bootstrap);
router.use('/superadmin', superadmin);
router.use('/users', users);
router.use('/hotels', hotels);
router.use('/menu', menu);
router.use('/categories', categories);
router.use('/tables', tables);
router.use('/stations', stations);
router.use('/taxes', taxes);
router.use('/general', general);
router.use('/orders', orders);
router.use('/invoices', invoices);
router.use('/notifications', notifications);
router.use('/bills', bills);
router.use('/dashboard', dashboard);
router.use('/debug', debug);
router.use('/reports', reports);

module.exports = router;
